# Generated by Django 5.1.1 on 2024-10-09 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='date',
        ),
        migrations.AddField(
            model_name='destination',
            name='date_from',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='destination',
            name='date_to',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
