# Generated by Django 5.1.1 on 2024-10-11 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantcomment',
            old_name='destination',
            new_name='restaurant',
        ),
    ]
