# Generated by Django 5.1.1 on 2024-10-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='image_url',
        ),
    ]
