# Generated by Django 5.1.1 on 2024-10-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_remove_hotel_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='destination',
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
