# Generated by Django 5.1.1 on 2024-10-13 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_comments', '0001_initial'),
        ('hotels', '0004_remove_hotel_destination_hotel_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelcomment',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_comments', to='hotels.hotel'),
        ),
    ]
